### ISSUE TITLE
no yarn recipe found

### ISSUE THREAD

**Issue by benlieb** [engineyard/ey-cookbooks-stable-v5#395]
I'm trying to follow the instructions provided here to install Yarn, but `custom-cookbooks/yarn/cookbooks/yarn` is not found in this repo. What am I missing?

```
# Yarn

This cookbook makes it easy to install any version of `yarn` available in a downloadable form in [https://github.com/yarnpkg/yarn/releases/](https://github.com/yarnpkg/yarn/releases/).

...

3. Copy `custom-cookbooks/timezone/cookbooks/yarn` to `cookbooks/`

```
    cd ~ # Change this to your preferred directory. Anywhere but inside the application

    git clone https://github.com/engineyard/ey-cookbooks-stable-v5
    cd ey-cookbooks-stable-v5
    cp custom-cookbooks/yarn/cookbooks/yarn /path/to/app/cookbooks/
```

If you do not have `cookbooks/ey-custom` on your app repository, you can copy
`custom-cookbooks/yarn/cookbooks/ey-custom` to `/path/to/app/cookbooks` as well.

## Specifying the Yarn version

The recipe is installing `yarn` version 1.9.4 by default. You may change that by setting the version in `cookbooks/yarn/attributes/default.rb`.


```

**Comment by giannoul** [comment]
Hello Benjamin,

The custom recipe for `yarn` is in the form of [Pull Request](https://github.com/engineyard/ey-cookbooks-stable-v5/pull/390) for the time being as it is evaluated in order to be merged for our next stack release.

The recipe itself will get you the desired `yarn` version installed (it has been tested and used) so you may get the contents of that PR in  a custom chef recipe, upload and apply it. The instructions for its installation are basically the same as the ones used by other EnginYard custom chef recipes for the `stable-v5` stack. Assuming that you want to use only the custom recipe for `yarn`, you will have to use the following structure locally (these are the contents of your `cookbooks` directory):

```
.
├── yarn
│   ├── attributes
│   │   └── default.rb
│   │ 
│   ├── files
│   │   └── default
│   │       └── yarn-generic.ebuild
│   ├── metadata.rb
│   ├──	README.md
│   └── recipes
│       └── default.rb
└── ey-custom
    ├── metadata.rb
    └── recipes
        └── after-main.rb
```
where the contents of the above files can be found in the PR. Uploading and applying should install  the `yarn` version that you have defined in `yarn/attributes/default.rb`.

**Comment by DalianisDim** [comment]
Yarn recipe is now included in custom-cookbooks. Added in release https://github.com/engineyard/ey-cookbooks-stable-v5/releases/tag/3.0.58
